spring:
  datasource:
    url: jdbc:mysql://localhost/street-cat-study?connectionCollation=utf8mb4_unicode_520_ci&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
  jpa:
    open-in-view: false
    show-sql: false

logging:
  level:
    root: info
